# Generated by Django 2.2.5 on 2024-01-16 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20240114_1512'),
    ]

    operations = [
    ]
