# Generated by Django 2.2.5 on 2024-01-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20240116_1323'),
    ]

    operations = [
    ]
